

interface Pagination($values: Object) {
    values: [$values!]!
}

type LengthAwarePaginator($values: Object) implements Pagination(values: $values) {
    perPage: Int!
    count: Int!
    values: [$values!]!
}

type Repository($typeOf: Object, $paginator: Pagination) {
    findAll: $paginator(values: $typeOf)!
    find(id: ID!): $typeOf
}

type UsersQuery {
    repository: Repository(typeOf: User, paginator: LengthAwarePaginator)
}
