namespace Test {


    type Outer {
        id: ID!
        value: String!

        type Ololo {
            scalar Inner
        }
    }

    type Example {
        type Another {
            scalar Test
        }
    }

}
