<?php
/**
 * This file is part of Parser package.
 * 
 * For the full copyright and license information, please view the
 * LICENSE file that was distributed with this source code.
 */
declare(strict_types=1);

namespace Railt\SDL\Parser;

use Railt\Compiler\Parser\Runtime as SchemaParserRuntime;
use Railt\Compiler\Lexer\NativeStateful as SchemaParserLexer;

/**
 * This class has been auto-generated by the Railt\Compiler\Generator
 */
final class SchemaParser extends SchemaParserRuntime
{
    /**#@+
     * List of SchemaParser::class tokens defined as public constants
     */
    public const T_AND = 'T_AND';
    public const T_OR = 'T_OR';
    public const T_PARENTHESIS_OPEN = 'T_PARENTHESIS_OPEN';
    public const T_PARENTHESIS_CLOSE = 'T_PARENTHESIS_CLOSE';
    public const T_BRACKET_OPEN = 'T_BRACKET_OPEN';
    public const T_BRACKET_CLOSE = 'T_BRACKET_CLOSE';
    public const T_BRACE_OPEN = 'T_BRACE_OPEN';
    public const T_BRACE_CLOSE = 'T_BRACE_CLOSE';
    public const T_NON_NULL = 'T_NON_NULL';
    public const T_THREE_DOTS = 'T_THREE_DOTS';
    public const T_COLON = 'T_COLON';
    public const T_EQUAL = 'T_EQUAL';
    public const T_DIRECTIVE_AT = 'T_DIRECTIVE_AT';
    public const T_NUMBER = 'T_NUMBER';
    public const T_TRUE = 'T_TRUE';
    public const T_FALSE = 'T_FALSE';
    public const T_NULL = 'T_NULL';
    public const T_BLOCK_STRING = 'T_BLOCK_STRING';
    public const T_STRING = 'T_STRING';
    public const T_NAMESPACE = 'T_NAMESPACE';
    public const T_NAMESPACE_SEPARATOR = 'T_NAMESPACE_SEPARATOR';
    public const T_EXTENDS = 'T_EXTENDS';
    public const T_IMPLEMENTS = 'T_IMPLEMENTS';
    public const T_ON = 'T_ON';
    public const T_TYPE = 'T_TYPE';
    public const T_ENUM = 'T_ENUM';
    public const T_UNION = 'T_UNION';
    public const T_INPUT_UNION = 'T_INPUT_UNION';
    public const T_INTERFACE = 'T_INTERFACE';
    public const T_SCHEMA = 'T_SCHEMA';
    public const T_SCALAR = 'T_SCALAR';
    public const T_DIRECTIVE = 'T_DIRECTIVE';
    public const T_INPUT = 'T_INPUT';
    public const T_EXTEND = 'T_EXTEND';
    public const T_FRAGMENT = 'T_FRAGMENT';
    public const T_VARIABLE = 'T_VARIABLE';
    public const T_NAME = 'T_NAME';
    public const T_WHITESPACE = 'T_WHITESPACE';
    public const T_COMMENT = 'T_COMMENT';
    public const T_COMMA = 'T_COMMA';
    /**#@-*/

    public function __construct()
    {
        parent::__construct(new SchemaParserLexer('/\\G(?P<T_AND>&)|(?P<T_OR>\\|)|(?P<T_PARENTHESIS_OPEN>\\()|(?P<T_PARENTHESIS_CLOSE>\\))|(?P<T_BRACKET_OPEN>\\[)|(?P<T_BRACKET_CLOSE>\\])|(?P<T_BRACE_OPEN>{)|(?P<T_BRACE_CLOSE>})|(?P<T_NON_NULL>!)|(?P<T_THREE_DOTS>\\.\\.\\.)|(?P<T_COLON>:)|(?P<T_EQUAL>=)|(?P<T_DIRECTIVE_AT>@)|(?P<T_NUMBER>\\-?(0|[1-9][0-9]*)(\\.[0-9]+)?([eE][\\+\\-]?[0-9]+)?\\b)|(?P<T_TRUE>true\\b)|(?P<T_FALSE>false\\b)|(?P<T_NULL>null\\b)|(?P<T_BLOCK_STRING>"""(?:\\\\"""|(?!""").|\\s)+""")|(?P<T_STRING>"[^"\\\\]+(\\\\.[^"\\\\]*)*")|(?P<T_NAMESPACE>namespace\\b)|(?P<T_NAMESPACE_SEPARATOR>\\/)|(?P<T_EXTENDS>extends\\b)|(?P<T_IMPLEMENTS>implements\\b)|(?P<T_ON>on\\b)|(?P<T_TYPE>type\\b)|(?P<T_ENUM>enum\\b)|(?P<T_UNION>union\\b)|(?P<T_INPUT_UNION>inputUnion\\b)|(?P<T_INTERFACE>interface\\b)|(?P<T_SCHEMA>schema\\b)|(?P<T_SCALAR>scalar\\b)|(?P<T_DIRECTIVE>directive\\b)|(?P<T_INPUT>input\\b)|(?P<T_EXTEND>extend\\b)|(?P<T_FRAGMENT>fragment\\b)|(?P<T_VARIABLE>\\$[_A-Za-z][_0-9A-Za-z]*)|(?P<T_NAME>[_A-Za-z][_0-9A-Za-z]*)|(?P<T_WHITESPACE>(\\xfe\\xff|\\x20|\\x09|\\x0a|\\x0d)+)|(?P<T_COMMENT>#[^\\n]*)|(?P<T_COMMA>,)|(?P<T_UNKNOWN>.*?)/usS', ['T_WHITESPACE','T_COMMENT','T_COMMA',]), [
                            0 =>
new \Railt\Compiler\Parser\Rule\Repetition(0, 0, -1, ['DocumentImports',], null),
                            1 =>
new \Railt\Compiler\Parser\Rule\Repetition(1, 0, -1, ['DocumentDefinitions',], null),
                            'Document' =>
new \Railt\Compiler\Parser\Rule\Concatenation('Document', [0,1,], '#Document'),
                            'DocumentImports' =>
new \Railt\Compiler\Parser\Rule\Concatenation('DocumentImports', ['Directive',], null),
                            'DocumentDefinitions' =>
new \Railt\Compiler\Parser\Rule\Alternation('DocumentDefinitions', ['Extension','Definition',], null),
                            5 =>
new \Railt\Compiler\Parser\Rule\Token(5, 'T_NAME', true),
                            'NameWithoutReserved' =>
new \Railt\Compiler\Parser\Rule\Concatenation('NameWithoutReserved', [5,], '#Name'),
                            7 =>
new \Railt\Compiler\Parser\Rule\Token(7, 'T_NAME', true),
                            8 =>
new \Railt\Compiler\Parser\Rule\Token(8, 'T_TRUE', true),
                            9 =>
new \Railt\Compiler\Parser\Rule\Token(9, 'T_FALSE', true),
                            10 =>
new \Railt\Compiler\Parser\Rule\Token(10, 'T_NULL', true),
                            11 =>
new \Railt\Compiler\Parser\Rule\Token(11, 'T_NAMESPACE', true),
                            12 =>
new \Railt\Compiler\Parser\Rule\Token(12, 'T_EXTENDS', true),
                            13 =>
new \Railt\Compiler\Parser\Rule\Token(13, 'T_IMPLEMENTS', true),
                            14 =>
new \Railt\Compiler\Parser\Rule\Token(14, 'T_ON', true),
                            15 =>
new \Railt\Compiler\Parser\Rule\Token(15, 'T_TYPE', true),
                            16 =>
new \Railt\Compiler\Parser\Rule\Token(16, 'T_ENUM', true),
                            17 =>
new \Railt\Compiler\Parser\Rule\Token(17, 'T_UNION', true),
                            18 =>
new \Railt\Compiler\Parser\Rule\Token(18, 'T_INPUT_UNION', true),
                            19 =>
new \Railt\Compiler\Parser\Rule\Token(19, 'T_INTERFACE', true),
                            20 =>
new \Railt\Compiler\Parser\Rule\Token(20, 'T_SCHEMA', true),
                            21 =>
new \Railt\Compiler\Parser\Rule\Token(21, 'T_SCALAR', true),
                            22 =>
new \Railt\Compiler\Parser\Rule\Token(22, 'T_DIRECTIVE', true),
                            23 =>
new \Railt\Compiler\Parser\Rule\Token(23, 'T_INPUT', true),
                            24 =>
new \Railt\Compiler\Parser\Rule\Token(24, 'T_EXTEND', true),
                            25 =>
new \Railt\Compiler\Parser\Rule\Token(25, 'T_FRAGMENT', true),
                            26 =>
new \Railt\Compiler\Parser\Rule\Alternation(26, [7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,], null),
                            'NameWithReserved' =>
new \Railt\Compiler\Parser\Rule\Concatenation('NameWithReserved', [26,], '#Name'),
                            28 =>
new \Railt\Compiler\Parser\Rule\Token(28, 'T_NAME', true),
                            29 =>
new \Railt\Compiler\Parser\Rule\Token(29, 'T_NAMESPACE', true),
                            30 =>
new \Railt\Compiler\Parser\Rule\Token(30, 'T_EXTENDS', true),
                            31 =>
new \Railt\Compiler\Parser\Rule\Token(31, 'T_IMPLEMENTS', true),
                            32 =>
new \Railt\Compiler\Parser\Rule\Token(32, 'T_ON', true),
                            33 =>
new \Railt\Compiler\Parser\Rule\Token(33, 'T_TYPE', true),
                            34 =>
new \Railt\Compiler\Parser\Rule\Token(34, 'T_ENUM', true),
                            35 =>
new \Railt\Compiler\Parser\Rule\Token(35, 'T_UNION', true),
                            36 =>
new \Railt\Compiler\Parser\Rule\Token(36, 'T_INPUT_UNION', true),
                            37 =>
new \Railt\Compiler\Parser\Rule\Token(37, 'T_INTERFACE', true),
                            38 =>
new \Railt\Compiler\Parser\Rule\Token(38, 'T_SCHEMA', true),
                            39 =>
new \Railt\Compiler\Parser\Rule\Token(39, 'T_SCALAR', true),
                            40 =>
new \Railt\Compiler\Parser\Rule\Token(40, 'T_DIRECTIVE', true),
                            41 =>
new \Railt\Compiler\Parser\Rule\Token(41, 'T_INPUT', true),
                            42 =>
new \Railt\Compiler\Parser\Rule\Token(42, 'T_EXTEND', true),
                            43 =>
new \Railt\Compiler\Parser\Rule\Token(43, 'T_FRAGMENT', true),
                            'NameExceptValues' =>
new \Railt\Compiler\Parser\Rule\Alternation('NameExceptValues', [28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,], null),
                            45 =>
new \Railt\Compiler\Parser\Rule\Token(45, 'T_VARIABLE', true),
                            'Variable' =>
new \Railt\Compiler\Parser\Rule\Concatenation('Variable', [45,], '#Variable'),
                            47 =>
new \Railt\Compiler\Parser\Rule\Repetition(47, 0, 1, ['TypeNamespace',], null),
                            'TypeName' =>
new \Railt\Compiler\Parser\Rule\Concatenation('TypeName', [47,'NameWithReserved',], '#TypeName'),
                            49 =>
new \Railt\Compiler\Parser\Rule\Token(49, 'T_NAMESPACE_SEPARATOR', false),
                            50 =>
new \Railt\Compiler\Parser\Rule\Concatenation(50, ['NameWithReserved',49,], '#TypeNamespace'),
                            'TypeNamespace' =>
new \Railt\Compiler\Parser\Rule\Repetition('TypeNamespace', 1, -1, [50,], null),
                            52 =>
new \Railt\Compiler\Parser\Rule\Token(52, 'T_FALSE', true),
                            53 =>
new \Railt\Compiler\Parser\Rule\Concatenation(53, [52,], '#Boolean'),
                            54 =>
new \Railt\Compiler\Parser\Rule\Token(54, 'T_TRUE', true),
                            55 =>
new \Railt\Compiler\Parser\Rule\Concatenation(55, [54,], '#Boolean'),
                            'Boolean' =>
new \Railt\Compiler\Parser\Rule\Alternation('Boolean', [53,55,], null),
                            57 =>
new \Railt\Compiler\Parser\Rule\Token(57, 'T_NUMBER', true),
                            'Number' =>
new \Railt\Compiler\Parser\Rule\Concatenation('Number', [57,], '#Number'),
                            59 =>
new \Railt\Compiler\Parser\Rule\Token(59, 'T_BLOCK_STRING', true),
                            60 =>
new \Railt\Compiler\Parser\Rule\Concatenation(60, [59,], '#String'),
                            61 =>
new \Railt\Compiler\Parser\Rule\Token(61, 'T_STRING', true),
                            62 =>
new \Railt\Compiler\Parser\Rule\Concatenation(62, [61,], '#String'),
                            'String' =>
new \Railt\Compiler\Parser\Rule\Alternation('String', [60,62,], null),
                            64 =>
new \Railt\Compiler\Parser\Rule\Token(64, 'T_NULL', true),
                            'Null' =>
new \Railt\Compiler\Parser\Rule\Concatenation('Null', [64,], '#Null'),
                            66 =>
new \Railt\Compiler\Parser\Rule\Token(66, 'T_BRACE_OPEN', false),
                            67 =>
new \Railt\Compiler\Parser\Rule\Repetition(67, 0, -1, ['__inputPair',], null),
                            68 =>
new \Railt\Compiler\Parser\Rule\Token(68, 'T_BRACE_CLOSE', false),
                            'Input' =>
new \Railt\Compiler\Parser\Rule\Concatenation('Input', [66,67,68,], '#Input'),
                            70 =>
new \Railt\Compiler\Parser\Rule\Token(70, 'T_COLON', false),
                            '__inputPair' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__inputPair', ['NameWithReserved',70,'Value',], '#Pair'),
                            72 =>
new \Railt\Compiler\Parser\Rule\Token(72, 'T_BRACKET_OPEN', false),
                            73 =>
new \Railt\Compiler\Parser\Rule\Repetition(73, 0, -1, ['Value',], null),
                            74 =>
new \Railt\Compiler\Parser\Rule\Token(74, 'T_BRACKET_CLOSE', false),
                            'List' =>
new \Railt\Compiler\Parser\Rule\Concatenation('List', [72,73,74,], '#List'),
                            76 =>
new \Railt\Compiler\Parser\Rule\Concatenation(76, ['NameWithReserved',], '#Value'),
                            77 =>
new \Railt\Compiler\Parser\Rule\Concatenation(77, ['Boolean',], '#Value'),
                            78 =>
new \Railt\Compiler\Parser\Rule\Concatenation(78, ['Number',], '#Value'),
                            79 =>
new \Railt\Compiler\Parser\Rule\Concatenation(79, ['String',], '#Value'),
                            80 =>
new \Railt\Compiler\Parser\Rule\Concatenation(80, ['Input',], '#Value'),
                            81 =>
new \Railt\Compiler\Parser\Rule\Concatenation(81, ['Null',], '#Value'),
                            82 =>
new \Railt\Compiler\Parser\Rule\Concatenation(82, ['List',], '#Value'),
                            'Value' =>
new \Railt\Compiler\Parser\Rule\Alternation('Value', [76,77,78,79,80,81,82,], null),
                            'Documentation' =>
new \Railt\Compiler\Parser\Rule\Concatenation('Documentation', ['String',], '#Description'),
                            85 =>
new \Railt\Compiler\Parser\Rule\Concatenation(85, ['__returnListDefinition',], '#ReturnTypeDefinition'),
                            86 =>
new \Railt\Compiler\Parser\Rule\Concatenation(86, ['__returnTypeDefinition',], '#ReturnTypeDefinition'),
                            'ReturnTypeDefinition' =>
new \Railt\Compiler\Parser\Rule\Alternation('ReturnTypeDefinition', [85,86,], null),
                            88 =>
new \Railt\Compiler\Parser\Rule\Token(88, 'T_NON_NULL', true),
                            '__returnTypeNonNullModifier' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__returnTypeNonNullModifier', [88,], '#NonNull'),
                            90 =>
new \Railt\Compiler\Parser\Rule\Token(90, 'T_BRACKET_OPEN', false),
                            91 =>
new \Railt\Compiler\Parser\Rule\Token(91, 'T_BRACKET_CLOSE', false),
                            92 =>
new \Railt\Compiler\Parser\Rule\Repetition(92, 0, 1, ['__returnTypeNonNullModifier',], null),
                            '__returnListDefinition' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__returnListDefinition', [90,'__returnTypeDefinition',91,92,], '#List'),
                            94 =>
new \Railt\Compiler\Parser\Rule\Repetition(94, 0, 1, ['__returnTypeDefinitionArguments',], null),
                            95 =>
new \Railt\Compiler\Parser\Rule\Concatenation(95, ['TypeName',94,], null),
                            96 =>
new \Railt\Compiler\Parser\Rule\Alternation(96, [95,'Variable',], null),
                            97 =>
new \Railt\Compiler\Parser\Rule\Repetition(97, 0, 1, ['__returnTypeNonNullModifier',], null),
                            '__returnTypeDefinition' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__returnTypeDefinition', [96,97,], '#Type'),
                            99 =>
new \Railt\Compiler\Parser\Rule\Token(99, 'T_PARENTHESIS_OPEN', false),
                            100 =>
new \Railt\Compiler\Parser\Rule\Repetition(100, 0, -1, ['ArgumentDefinition',], null),
                            101 =>
new \Railt\Compiler\Parser\Rule\Token(101, 'T_PARENTHESIS_CLOSE', false),
                            '__returnTypeDefinitionArguments' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__returnTypeDefinitionArguments', [99,100,101,], '#TypeArguments'),
                            103 =>
new \Railt\Compiler\Parser\Rule\Token(103, 'T_IMPLEMENTS', false),
                            104 =>
new \Railt\Compiler\Parser\Rule\Token(104, 'T_AND', false),
                            105 =>
new \Railt\Compiler\Parser\Rule\Concatenation(105, [104,'TypeName',], null),
                            106 =>
new \Railt\Compiler\Parser\Rule\Repetition(106, 0, -1, [105,], null),
                            'TypeDefinitionImplements' =>
new \Railt\Compiler\Parser\Rule\Concatenation('TypeDefinitionImplements', [103,'TypeName',106,], null),
                            108 =>
new \Railt\Compiler\Parser\Rule\Token(108, 'T_PARENTHESIS_OPEN', false),
                            109 =>
new \Railt\Compiler\Parser\Rule\Repetition(109, 0, -1, ['__genericArgumentDefinition',], null),
                            110 =>
new \Railt\Compiler\Parser\Rule\Token(110, 'T_PARENTHESIS_CLOSE', false),
                            'GenericArgumentsDefinition' =>
new \Railt\Compiler\Parser\Rule\Concatenation('GenericArgumentsDefinition', [108,109,110,], null),
                            112 =>
new \Railt\Compiler\Parser\Rule\Token(112, 'T_COLON', false),
                            '__genericArgumentDefinition' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__genericArgumentDefinition', ['Variable',112,'TypeName',], '#GenericArgument'),
                            114 =>
new \Railt\Compiler\Parser\Rule\Repetition(114, 0, 1, ['Documentation',], null),
                            115 =>
new \Railt\Compiler\Parser\Rule\Token(115, 'T_COLON', false),
                            116 =>
new \Railt\Compiler\Parser\Rule\Repetition(116, 0, 1, ['__argumentDefinitionDefaultValue',], null),
                            'ArgumentDefinition' =>
new \Railt\Compiler\Parser\Rule\Concatenation('ArgumentDefinition', [114,'NameWithReserved',115,'ReturnTypeDefinition',116,], '#ArgumentDefinition'),
                            118 =>
new \Railt\Compiler\Parser\Rule\Token(118, 'T_EQUAL', false),
                            '__argumentDefinitionDefaultValue' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__argumentDefinitionDefaultValue', [118,'Value',], null),
                            120 =>
new \Railt\Compiler\Parser\Rule\Repetition(120, 0, 1, ['Documentation',], null),
                            121 =>
new \Railt\Compiler\Parser\Rule\Repetition(121, 0, 1, ['__fieldDefinitionArguments',], null),
                            122 =>
new \Railt\Compiler\Parser\Rule\Token(122, 'T_COLON', false),
                            123 =>
new \Railt\Compiler\Parser\Rule\Repetition(123, 0, -1, ['Directive',], null),
                            'FieldDefinition' =>
new \Railt\Compiler\Parser\Rule\Concatenation('FieldDefinition', [120,'NameWithReserved',121,122,'ReturnTypeDefinition',123,], '#FieldDefinition'),
                            125 =>
new \Railt\Compiler\Parser\Rule\Token(125, 'T_PARENTHESIS_OPEN', false),
                            126 =>
new \Railt\Compiler\Parser\Rule\Repetition(126, 0, -1, ['__fieldDefinitionArgument',], null),
                            127 =>
new \Railt\Compiler\Parser\Rule\Token(127, 'T_PARENTHESIS_CLOSE', false),
                            '__fieldDefinitionArguments' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__fieldDefinitionArguments', [125,126,127,], null),
                            129 =>
new \Railt\Compiler\Parser\Rule\Repetition(129, 0, -1, ['Directive',], null),
                            '__fieldDefinitionArgument' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__fieldDefinitionArgument', ['ArgumentDefinition',129,], null),
                            131 =>
new \Railt\Compiler\Parser\Rule\Repetition(131, 0, 1, ['Documentation',], null),
                            'DirectiveDefinition' =>
new \Railt\Compiler\Parser\Rule\Concatenation('DirectiveDefinition', [131,'DirectiveDefinitionBody',], '#DirectiveDefinition'),
                            133 =>
new \Railt\Compiler\Parser\Rule\Token(133, 'T_DIRECTIVE', false),
                            134 =>
new \Railt\Compiler\Parser\Rule\Token(134, 'T_DIRECTIVE_AT', false),
                            135 =>
new \Railt\Compiler\Parser\Rule\Repetition(135, 0, 1, ['__directiveDefinitionArguments',], null),
                            136 =>
new \Railt\Compiler\Parser\Rule\Token(136, 'T_ON', false),
                            'DirectiveDefinitionBody' =>
new \Railt\Compiler\Parser\Rule\Concatenation('DirectiveDefinitionBody', [133,134,'TypeName',135,136,'__directiveDefinitionLocations',], null),
                            138 =>
new \Railt\Compiler\Parser\Rule\Token(138, 'T_PARENTHESIS_OPEN', false),
                            139 =>
new \Railt\Compiler\Parser\Rule\Repetition(139, 0, -1, ['__directiveDefinitionArgument',], null),
                            140 =>
new \Railt\Compiler\Parser\Rule\Token(140, 'T_PARENTHESIS_CLOSE', false),
                            '__directiveDefinitionArguments' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__directiveDefinitionArguments', [138,139,140,], null),
                            '__directiveDefinitionArgument' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__directiveDefinitionArgument', ['ArgumentDefinition',], '#DirectiveArgument'),
                            143 =>
new \Railt\Compiler\Parser\Rule\Token(143, 'T_OR', false),
                            144 =>
new \Railt\Compiler\Parser\Rule\Repetition(144, 0, 1, [143,], null),
                            145 =>
new \Railt\Compiler\Parser\Rule\Repetition(145, 1, -1, ['__directiveDefinitionLocation',], null),
                            '__directiveDefinitionLocations' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__directiveDefinitionLocations', [144,145,], '#DirectiveLocations'),
                            147 =>
new \Railt\Compiler\Parser\Rule\Token(147, 'T_OR', false),
                            148 =>
new \Railt\Compiler\Parser\Rule\Concatenation(148, [147,'NameWithReserved',], null),
                            149 =>
new \Railt\Compiler\Parser\Rule\Repetition(149, 0, -1, [148,], null),
                            '__directiveDefinitionLocation' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__directiveDefinitionLocation', ['NameWithReserved',149,], null),
                            151 =>
new \Railt\Compiler\Parser\Rule\Repetition(151, 0, 1, ['Documentation',], null),
                            'EnumDefinition' =>
new \Railt\Compiler\Parser\Rule\Concatenation('EnumDefinition', [151,'EnumDefinitionHead','EnumDefinitionBody',], '#EnumDefinition'),
                            153 =>
new \Railt\Compiler\Parser\Rule\Token(153, 'T_ENUM', false),
                            154 =>
new \Railt\Compiler\Parser\Rule\Repetition(154, 0, -1, ['Directive',], null),
                            'EnumDefinitionHead' =>
new \Railt\Compiler\Parser\Rule\Concatenation('EnumDefinitionHead', [153,'TypeName',154,], null),
                            156 =>
new \Railt\Compiler\Parser\Rule\Token(156, 'T_BRACE_OPEN', false),
                            157 =>
new \Railt\Compiler\Parser\Rule\Repetition(157, 1, -1, ['__enumDefinitionValue',], null),
                            158 =>
new \Railt\Compiler\Parser\Rule\Token(158, 'T_BRACE_CLOSE', false),
                            'EnumDefinitionBody' =>
new \Railt\Compiler\Parser\Rule\Concatenation('EnumDefinitionBody', [156,157,158,], null),
                            160 =>
new \Railt\Compiler\Parser\Rule\Repetition(160, 0, 1, ['Documentation',], null),
                            161 =>
new \Railt\Compiler\Parser\Rule\Repetition(161, 0, -1, ['Directive',], null),
                            '__enumDefinitionValue' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__enumDefinitionValue', [160,'NameExceptValues',161,], '#EnumValue'),
                            163 =>
new \Railt\Compiler\Parser\Rule\Repetition(163, 0, 1, ['Documentation',], null),
                            'InputDefinition' =>
new \Railt\Compiler\Parser\Rule\Concatenation('InputDefinition', [163,'InputDefinitionHead','InputDefinitionBody',], '#InputDefinition'),
                            165 =>
new \Railt\Compiler\Parser\Rule\Token(165, 'T_INPUT', false),
                            166 =>
new \Railt\Compiler\Parser\Rule\Repetition(166, 0, -1, ['Directive',], null),
                            'InputDefinitionHead' =>
new \Railt\Compiler\Parser\Rule\Concatenation('InputDefinitionHead', [165,'TypeName',166,], null),
                            168 =>
new \Railt\Compiler\Parser\Rule\Token(168, 'T_BRACE_OPEN', false),
                            169 =>
new \Railt\Compiler\Parser\Rule\Repetition(169, 0, -1, ['__inputDefinitionField',], null),
                            170 =>
new \Railt\Compiler\Parser\Rule\Token(170, 'T_BRACE_CLOSE', false),
                            'InputDefinitionBody' =>
new \Railt\Compiler\Parser\Rule\Concatenation('InputDefinitionBody', [168,169,170,], null),
                            172 =>
new \Railt\Compiler\Parser\Rule\Repetition(172, 0, -1, ['Directive',], null),
                            '__inputDefinitionField' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__inputDefinitionField', ['ArgumentDefinition',172,], '#InputField'),
                            174 =>
new \Railt\Compiler\Parser\Rule\Repetition(174, 0, 1, ['Documentation',], null),
                            'InterfaceDefinition' =>
new \Railt\Compiler\Parser\Rule\Concatenation('InterfaceDefinition', [174,'InterfaceDefinitionHead','InterfaceDefinitionBody',], '#InterfaceDefinition'),
                            176 =>
new \Railt\Compiler\Parser\Rule\Token(176, 'T_INTERFACE', false),
                            177 =>
new \Railt\Compiler\Parser\Rule\Repetition(177, 0, 1, ['GenericArgumentsDefinition',], null),
                            178 =>
new \Railt\Compiler\Parser\Rule\Repetition(178, 0, 1, ['TypeDefinitionImplements',], null),
                            179 =>
new \Railt\Compiler\Parser\Rule\Repetition(179, 0, -1, ['Directive',], null),
                            'InterfaceDefinitionHead' =>
new \Railt\Compiler\Parser\Rule\Concatenation('InterfaceDefinitionHead', [176,'TypeName',177,178,179,], null),
                            181 =>
new \Railt\Compiler\Parser\Rule\Token(181, 'T_BRACE_OPEN', false),
                            182 =>
new \Railt\Compiler\Parser\Rule\Repetition(182, 0, -1, ['FieldDefinition',], null),
                            183 =>
new \Railt\Compiler\Parser\Rule\Token(183, 'T_BRACE_CLOSE', false),
                            'InterfaceDefinitionBody' =>
new \Railt\Compiler\Parser\Rule\Concatenation('InterfaceDefinitionBody', [181,182,183,], null),
                            185 =>
new \Railt\Compiler\Parser\Rule\Repetition(185, 0, 1, ['Documentation',], null),
                            'ObjectDefinition' =>
new \Railt\Compiler\Parser\Rule\Concatenation('ObjectDefinition', [185,'ObjectDefinitionHead','ObjectDefinitionBody',], '#ObjectDefinition'),
                            187 =>
new \Railt\Compiler\Parser\Rule\Token(187, 'T_TYPE', false),
                            188 =>
new \Railt\Compiler\Parser\Rule\Repetition(188, 0, 1, ['GenericArgumentsDefinition',], null),
                            189 =>
new \Railt\Compiler\Parser\Rule\Repetition(189, 0, 1, ['TypeDefinitionImplements',], null),
                            190 =>
new \Railt\Compiler\Parser\Rule\Repetition(190, 0, -1, ['Directive',], null),
                            'ObjectDefinitionHead' =>
new \Railt\Compiler\Parser\Rule\Concatenation('ObjectDefinitionHead', [187,'TypeName',188,189,190,], null),
                            192 =>
new \Railt\Compiler\Parser\Rule\Token(192, 'T_BRACE_OPEN', false),
                            193 =>
new \Railt\Compiler\Parser\Rule\Repetition(193, 0, -1, ['FieldDefinition',], null),
                            194 =>
new \Railt\Compiler\Parser\Rule\Token(194, 'T_BRACE_CLOSE', false),
                            'ObjectDefinitionBody' =>
new \Railt\Compiler\Parser\Rule\Concatenation('ObjectDefinitionBody', [192,193,194,], null),
                            196 =>
new \Railt\Compiler\Parser\Rule\Repetition(196, 0, 1, ['Documentation',], null),
                            'ScalarDefinition' =>
new \Railt\Compiler\Parser\Rule\Concatenation('ScalarDefinition', [196,'ScalarDefinitionBody',], '#ScalarDefinition'),
                            198 =>
new \Railt\Compiler\Parser\Rule\Token(198, 'T_SCALAR', false),
                            199 =>
new \Railt\Compiler\Parser\Rule\Repetition(199, 0, 1, ['__scalarExtends',], null),
                            200 =>
new \Railt\Compiler\Parser\Rule\Repetition(200, 0, -1, ['Directive',], null),
                            'ScalarDefinitionBody' =>
new \Railt\Compiler\Parser\Rule\Concatenation('ScalarDefinitionBody', [198,'TypeName',199,200,], null),
                            202 =>
new \Railt\Compiler\Parser\Rule\Token(202, 'T_EXTENDS', false),
                            '__scalarExtends' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__scalarExtends', [202,'TypeName',], '#Extends'),
                            204 =>
new \Railt\Compiler\Parser\Rule\Repetition(204, 0, 1, ['Documentation',], null),
                            'SchemaDefinition' =>
new \Railt\Compiler\Parser\Rule\Concatenation('SchemaDefinition', [204,'SchemaDefinitionBody',], '#SchemaDefinition'),
                            206 =>
new \Railt\Compiler\Parser\Rule\Token(206, 'T_SCHEMA', false),
                            207 =>
new \Railt\Compiler\Parser\Rule\Repetition(207, 0, 1, ['TypeName',], null),
                            208 =>
new \Railt\Compiler\Parser\Rule\Token(208, 'T_BRACE_OPEN', false),
                            209 =>
new \Railt\Compiler\Parser\Rule\Repetition(209, 0, -1, ['__schemaField',], null),
                            210 =>
new \Railt\Compiler\Parser\Rule\Token(210, 'T_BRACE_CLOSE', false),
                            'SchemaDefinitionBody' =>
new \Railt\Compiler\Parser\Rule\Concatenation('SchemaDefinitionBody', [206,207,208,209,210,], null),
                            212 =>
new \Railt\Compiler\Parser\Rule\Token(212, 'T_COLON', false),
                            '__schemaField' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__schemaField', ['NameWithReserved',212,'TypeName',], '#SchemaField'),
                            214 =>
new \Railt\Compiler\Parser\Rule\Repetition(214, 0, 1, ['Documentation',], null),
                            'UnionDefinition' =>
new \Railt\Compiler\Parser\Rule\Concatenation('UnionDefinition', [214,'UnionDefinitionBody',], '#UnionDefinition'),
                            216 =>
new \Railt\Compiler\Parser\Rule\Token(216, 'T_UNION', false),
                            217 =>
new \Railt\Compiler\Parser\Rule\Repetition(217, 0, -1, ['Directive',], null),
                            218 =>
new \Railt\Compiler\Parser\Rule\Token(218, 'T_EQUAL', false),
                            219 =>
new \Railt\Compiler\Parser\Rule\Token(219, 'T_OR', false),
                            220 =>
new \Railt\Compiler\Parser\Rule\Repetition(220, 0, 1, [219,], null),
                            221 =>
new \Railt\Compiler\Parser\Rule\Repetition(221, 1, -1, ['__unionDefinitionTargets',], null),
                            'UnionDefinitionBody' =>
new \Railt\Compiler\Parser\Rule\Concatenation('UnionDefinitionBody', [216,'TypeName',217,218,220,221,], null),
                            223 =>
new \Railt\Compiler\Parser\Rule\Token(223, 'T_OR', false),
                            224 =>
new \Railt\Compiler\Parser\Rule\Concatenation(224, [223,'TypeName',], null),
                            225 =>
new \Railt\Compiler\Parser\Rule\Repetition(225, 0, -1, [224,], null),
                            '__unionDefinitionTargets' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__unionDefinitionTargets', ['TypeName',225,], null),
                            'Definition' =>
new \Railt\Compiler\Parser\Rule\Alternation('Definition', ['DirectiveDefinition','EnumDefinition','InputDefinition','InterfaceDefinition','ObjectDefinition','ScalarDefinition','SchemaDefinition','UnionDefinition',], null),
                            228 =>
new \Railt\Compiler\Parser\Rule\Token(228, 'T_EXTEND', false),
                            'EnumExtension' =>
new \Railt\Compiler\Parser\Rule\Concatenation('EnumExtension', [228,'__enumExtensionVariants',], '#EnumExtension'),
                            230 =>
new \Railt\Compiler\Parser\Rule\Concatenation(230, ['EnumDefinitionHead','EnumDefinitionBody',], null),
                            '__enumExtensionVariants' =>
new \Railt\Compiler\Parser\Rule\Alternation('__enumExtensionVariants', ['EnumDefinitionHead',230,], null),
                            232 =>
new \Railt\Compiler\Parser\Rule\Token(232, 'T_EXTEND', false),
                            'InputExtension' =>
new \Railt\Compiler\Parser\Rule\Concatenation('InputExtension', [232,'__inputExtensionVariants',], '#InputExtension'),
                            234 =>
new \Railt\Compiler\Parser\Rule\Concatenation(234, ['InputDefinitionHead','InputDefinitionBody',], null),
                            '__inputExtensionVariants' =>
new \Railt\Compiler\Parser\Rule\Alternation('__inputExtensionVariants', ['InputDefinitionHead',234,], null),
                            236 =>
new \Railt\Compiler\Parser\Rule\Token(236, 'T_EXTEND', false),
                            'InterfaceExtension' =>
new \Railt\Compiler\Parser\Rule\Concatenation('InterfaceExtension', [236,'__interfaceExtensionVariants',], '#InterfaceExtension'),
                            238 =>
new \Railt\Compiler\Parser\Rule\Concatenation(238, ['InterfaceDefinitionHead','InterfaceDefinitionBody',], null),
                            '__interfaceExtensionVariants' =>
new \Railt\Compiler\Parser\Rule\Alternation('__interfaceExtensionVariants', ['InterfaceDefinitionHead',238,], null),
                            240 =>
new \Railt\Compiler\Parser\Rule\Token(240, 'T_EXTEND', false),
                            'ObjectExtension' =>
new \Railt\Compiler\Parser\Rule\Concatenation('ObjectExtension', [240,'__objectExtensionVariants',], '#ObjectExtension'),
                            242 =>
new \Railt\Compiler\Parser\Rule\Concatenation(242, ['ObjectDefinitionHead','ObjectDefinitionBody',], null),
                            '__objectExtensionVariants' =>
new \Railt\Compiler\Parser\Rule\Alternation('__objectExtensionVariants', ['ObjectDefinitionHead',242,], null),
                            244 =>
new \Railt\Compiler\Parser\Rule\Token(244, 'T_EXTEND', false),
                            'ScalarExtension' =>
new \Railt\Compiler\Parser\Rule\Concatenation('ScalarExtension', [244,'ScalarDefinitionBody',], '#ScalarExtension'),
                            246 =>
new \Railt\Compiler\Parser\Rule\Token(246, 'T_EXTEND', false),
                            'SchemaExtension' =>
new \Railt\Compiler\Parser\Rule\Concatenation('SchemaExtension', [246,'SchemaDefinitionBody',], '#SchemaExtension'),
                            248 =>
new \Railt\Compiler\Parser\Rule\Token(248, 'T_EXTEND', false),
                            'UnionExtension' =>
new \Railt\Compiler\Parser\Rule\Concatenation('UnionExtension', [248,'UnionDefinitionBody',], '#UnionExtension'),
                            'Extension' =>
new \Railt\Compiler\Parser\Rule\Alternation('Extension', ['EnumExtension','InputExtension','InterfaceExtension','ObjectExtension','ScalarExtension','SchemaExtension','UnionExtension',], null),
                            251 =>
new \Railt\Compiler\Parser\Rule\Token(251, 'T_COLON', false),
                            'ArgumentInvocation' =>
new \Railt\Compiler\Parser\Rule\Concatenation('ArgumentInvocation', ['NameWithReserved',251,'Value',], null),
                            253 =>
new \Railt\Compiler\Parser\Rule\Token(253, 'T_DIRECTIVE_AT', false),
                            254 =>
new \Railt\Compiler\Parser\Rule\Repetition(254, 0, 1, ['__directiveInvocationArguments',], null),
                            'Directive' =>
new \Railt\Compiler\Parser\Rule\Concatenation('Directive', [253,'TypeName',254,], '#Directive'),
                            256 =>
new \Railt\Compiler\Parser\Rule\Token(256, 'T_PARENTHESIS_OPEN', false),
                            257 =>
new \Railt\Compiler\Parser\Rule\Repetition(257, 0, -1, ['__directiveInvocationArgument',], null),
                            258 =>
new \Railt\Compiler\Parser\Rule\Token(258, 'T_PARENTHESIS_CLOSE', false),
                            '__directiveInvocationArguments' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__directiveInvocationArguments', [256,257,258,], null),
                            '__directiveInvocationArgument' =>
new \Railt\Compiler\Parser\Rule\Concatenation('__directiveInvocationArgument', ['ArgumentInvocation',], '#DirectiveArgument'),
                            'Invocation' =>
new \Railt\Compiler\Parser\Rule\Concatenation('Invocation', ['Directive',], null),
                    ]);
    }

    /**
     * @return string Returns the lexer compilation date and time in RFC3339 format
     */
    public function getBuiltDate(): string
    {
        return '2018-05-11MSK16:48:36.808+03:00';
    }
}
